version: "3"

services:
  db:
    image: mariadb:10.4.13
    ports:
      - "3310:3306"
    restart: always
    environment:
      TZ: Asia/Seoul
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: study

